name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  REGISTRY: "cr.selcloud.ru/test"
  IMAGE_NAME: "serverx"
  CONTAINER_NAME: "test-container"

jobs:
  image_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4.1.1

      - name: setup docker v3
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and push Docker image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --platform linux/amd64 --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME .

  deploy-image:
      runs-on: ubuntu-latest
      needs: image_build_and_push

      steps:
        - name: Deploy to Selectel cloud via SSH action
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            envs: IMAGE_NAME,REGISTRY,CONTAINER_NAME
            script: |
              TAG_NAME=$(echo $GITHUB_SHA | head -c7)
              docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
              docker run -d -p 80:1323 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME
